version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=3000 --host=0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      -







































